install.packages("dlookr")
install.packages("rworldmap")
install.packages("tm")
install.packages("evaluate")
install.packages("wordcloud")
install.packages("ggmosaic")
install.packages("ggpubr")
install.packages("apyramid")
install.packages("pscl")
install.packages("rpart")
install.packages("rsample")
install.packages("recipes")
install.packages("ggeffects")
install.packages("effects")
install.packages('caret')
install.packages('Information')
install.packages('car')
install.packages('pROC')

devtools::install_github("selva86/InformationValue")

library(tm)  
library(dplyr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(dlookr)
library(evaluate)
library(rworldmap)
library(wordcloud)  
library(ggmosaic)
library(ggpubr)
library(apyramid)
library(pscl)
library(rsample)
library(rpart)
library(recipes)
library(ggeffects)
library(effects)
library(caret)
library(InformationValue)
library(pROC)
library(car)

set.seed(64)

### Setting files for analysis
#PS: the path should be change if project is downloaded and doubled slash are required in Windows based systems
#setwd("J:\\IFSP\\ICD6-ciencia-de-dados\\projeto-final-ciencia-de-dados-datasets\\mental-health-in-tech-industry")
#$getwd()

answers <- read.csv("J:\\Code\\faculdade\\ICD6-ciencia-de-dados\\projeto-final\\MentalHealthInTechIndustry\\MentalHealthTechIndustrySurvey\\Surveys\\mental-health-answers.csv", na.string="", stringsAsFactors=F)
questions <- read.csv("J:\\Code\\faculdade\\ICD6-ciencia-de-dados\\projeto-final\\MentalHealthInTechIndustry\\MentalHealthTechIndustrySurvey\\Surveys\\mental-health-question.csv",  na.string="", stringsAsFactors=F)
survey <- read.csv("J:\\Code\\faculdade\\ICD6-ciencia-de-dados\\projeto-final\\MentalHealthInTechIndustry\\MentalHealthTechIndustrySurvey\\Surveys\\mental-health-survey.csv", na.string="", stringsAsFactors=F)
